apiVersion: apps/v1
kind: Deployment
metadata:
  name: chekin-backend-cloudbeds
  labels:
    app: chekin-backend-cloudbeds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chekin-backend-cloudbeds
  template:
    metadata:
      labels:
        app: chekin-backend-cloudbeds
    spec:
      priorityClassName: chekin-services
      containers:
      - name: chekin-backend-cloudbeds
        image: 358099927528.dkr.ecr.eu-central-1.amazonaws.com/chekin-cloudbeds:staging
        imagePullPolicy: Always
        resources:
            limits:
                memory: "200Mi"
                ephemeral-storage: "300Mi"
            requests:
                memory: "100Mi"
                ephemeral-storage: "100Mi"
        env:
        - name: ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: config-env-hosts
              key: allowed_hosts
        - name: WEBSOCKETS_ENABLED
          value: '1'
        - name: DB_NAME
          value: 'staging-integrations-cloudbeds'
        - name: URL_PREFIX
          value: 'api/v3/cloudbeds/'
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: auth-db
              key: username
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-server
              key: jwt_secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-db
              key: password
        - name: DB_HOST
          value: postgres-svc
        - name: DB_PORT
          value: '5432'
        - name: MAIN_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: config-env-hosts
              key: main_domain
        - name: DASHBOARD
          valueFrom:
            configMapKeyRef:
              name: config-env-hosts
              key: dashboard
        - name: CORE_HOST
          value: https://$(MAIN_DOMAIN)/api/v3/
        - name: CLOUDBEDS_API_URL
          value: https://hotels.cloudbeds.com/api/v1.1/
        - name: CLOUDBEDS_CLIENT_ID
          value: chekin_test_CR7gBI2Uku1amorJSdM6FGXH
        - name: CLOUDBEDS_REDIRECT_URL
          value: $(DASHBOARD)/register/pms/cloudbeds-sync
        - name: CLOUDBEDS_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: cloudbeds-auth
              key: secret
        - name: RABBIT_HOST
          valueFrom:
            secretKeyRef:
              name: auth-rabbitmq
              key: host
        - name: RABBIT_USER
          valueFrom:
            secretKeyRef:
              name: auth-rabbitmq
              key: username
        - name: RABBIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-rabbitmq
              key: password
        - name: RABBIT_PORT
          valueFrom:
            secretKeyRef:
              name: auth-rabbitmq
              key: port
        - name: EXCHANGE_TO_CLOUDBEDS_WORKER
          valueFrom:
              configMapKeyRef:
                  name: config-env-rabbit
                  key: pms.exchange
        - name: ROUTING_KEY_TO_CLOUDBEDS_WORKER
          valueFrom:
              configMapKeyRef:
                  name: config-env-rabbit
                  key: cloudbeds.routing_key
        - name: CLOUDBEDS_SERVICE_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudbeds-service-token
              key: token
        ports:
          - name: http
            protocol: TCP
            containerPort: 8000
      imagePullSecrets:
      - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: chekin-backend-cloudbeds
  labels:
    app: chekin-backend-cloudbeds
spec:
  type: NodePort
  ports:
   - name: http
     protocol: TCP
     port: 8000
     targetPort: 8000
     nodePort: 32650
  selector:
    app: chekin-backend-cloudbeds
